PYDOC = pydoc3

pydoc:
	$(PYDOC) -w Gui
	$(PYDOC) -w World
	$(PYDOC) -w TurtleWorld
	$(PYDOC) -w CellWorld
	$(PYDOC) -w TurmiteWorld
	$(PYDOC) -w AmoebaWorld
	$(PYDOC) -w Sync
	$(PYDOC) -w Lumpy

clean:
	rm *~ *.pyc